# Site settings
title: Once upon a time
email: murat.dbc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Murat Gocmen is blogger,tech Enthusiast and Tango Afficionado
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://muratdbc.github.io" # the base hostname & protocol for your site
twitter_username: GocmenMurat
github_username:  muratdbc

# Build settings
markdown: kramdown
